run:
  concurrency: 4
  timeout: 10m
  issue-exit-code: 1
  tests: true
  go: '1.20'

output:
  sort-results: true

linters:
  disable-all: true
  fast: false
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - asciicheck
    - bidichk
    - bodyclose
    - contextcheck
    - cyclop
    - errname
    - errorlint
    - exhaustive
    - exportloopref
    - forcetypeassert
    - goconst
    - goimports
    - gosec
    - misspell
    - musttag
    - paralleltest
    - prealloc
    - unconvert
    - usestdlibvars

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true
  gosimple:
    go: "1.20"
  govet:
    check-shadowing: true
    enable-all: true
    disable:
      - fieldalignment
  staticcheck:
    go: "1.20"
    checks:
      - all
  cyclop:
    skip-tests: true
  exhaustive:
    default-signifies-exhaustive: true
  goconst:
    ignore-tests: true
  goimports:
    local-prefixes: github.com/thepabloaguilar/moki
  misspell:
    locale: US
  paralleltest:
    ignore-missing-subtests: true

issues:
  fix: true
