version: '3.0'

services:
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: moki
      POSTGRES_PASSWORD: moki
      POSTGRES_DB: moki
    ports:
      - "5432:5432"
